version: '3'

services:

  server:
    container_name: server
    image: madduci/docker-ubuntu-cpp:gcc-6
    networks:
      project:
        aliases:
          - server.local
    entrypoint:
    volumes:
      - ./:/project

  client_1:
    container_name: client_1
    image: madduci/docker-ubuntu-cpp:gcc-6
    networks:
      project:
        aliases:
          - client1.local
    entrypoint:
    volumes:
      - ./:/project

  client_2:
    container_name: client_2
    image: madduci/docker-ubuntu-cpp:gcc-6
    networks:
      project:
        aliases:
          - client2.local
    entrypoint:
    volumes:
      - ./:/project

networks:
  project:
    driver: bridge