version: '3'

services:

  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./internals/Client/Dockerfile
    networks:
      project:
        aliases:
          - server.local
    volumes:
      - ./:/project

  client_1:
    container_name: client_1
    build:
      context: ./
      dockerfile: ./internals/Client/Dockerfile
    networks:
      project:
        aliases:
          - client1.local
    entrypoint:
    volumes:
      - ./:/project

  client_2:
    container_name: client_2
    build:
      context: ./
      dockerfile: ./internals/Client/Dockerfile
    networks:
      project:
        aliases:
          - client2.local
    entrypoint:
    volumes:
      - ./:/project

networks:
  project:
    driver: bridge