version: '3'

services:

  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./internals/Server/Dockerfile
    networks:
      project:
        aliases:
          - server.local
    volumes:
      - ./:/project

  client_1:
    container_name: client_1
    build:
      context: ./
      dockerfile: ./internals/Client/Dockerfile
    networks:
      project:
        aliases:
          - nginx.local
    volumes:
      - ./:/project
    entrypoint: nginx -g "daemon off;"

  client_2:
    container_name: client_2
    build:
      context: ./
      dockerfile: ./internals/Client/Dockerfile
    networks:
      project:
        aliases:
          - supervisor.local
    volumes:
      - ./:/project
    entrypoint: supervisord -n

networks:
  project:
    driver: bridge